[auth]
algorithm = "HS256"
secret = "your_secret_key"
expiration = 3600

[server]
port = 25565

[ssl]
enable = true
cert_path = "./certs/cert.pem"
key_path  = "./certs/key.pem"

[database]
type = "Sqlite" # Options: "Postgres", "Sqlite"

# password = "root"
database = "output.db"
